const $=s=>document.querySelector(s);const state={base:'',auth:''};
function base(){return $('#baseUrl').value.trim().replace(/\/$/,'')||'http://192.168.4.1'}
function headers(){return state.auth?{Authorization:`Basic ${state.auth}`}:{} }
async function api(path,options={}){const r=await fetch(state.base+path,{...options,headers:{...headers(),...(options.headers||{})},credentials:'include',cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r}
function setStatus(id,msg,kind=''){const e=$(id);e.textContent=msg;e.className='status '+kind}
$('#connect').onclick=async()=>{state.base=base();state.auth=btoa(`${$('#username').value}:${$('#password').value}`);setStatus('#connectionStatus','Checking sign…');try{const r=await api('/api/status');const d=await r.json();setStatus('#connectionStatus',`Connected · ${d.ip||state.base}`,'ok')}catch(e){setStatus('#connectionStatus',`Could not connect: ${e.message}. If this page is on GitHub Pages, use the device portal at http://192.168.4.1 instead.`,'error')}};
const fields=['flight_number','codeshare','departure_en','destination_en','departure_time','status_en'];function preview(){const f=new FormData($('#flightForm'));$('#previewFlight').textContent=f.get('flight_number');$('#previewFrom').textContent=f.get('departure_en');$('#previewTo').textContent=f.get('destination_en');$('#previewCode').textContent=f.get('codeshare')||'—';$('#previewStatus').textContent=(f.get('status_en')||'').toUpperCase();}fields.forEach(n=>$(`[name=${n}]`).addEventListener('input',preview));preview();
$('#flightForm').onsubmit=async e=>{e.preventDefault();if(!state.base)state.base=base();setStatus('#flightStatus','Saving…');try{const body=new URLSearchParams(new FormData(e.target));body.set('save_scope','flight');await api('/api/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});setStatus('#flightStatus','Saved. The LCD will use the new flight data.','ok')}catch(err){setStatus('#flightStatus',`Save failed: ${err.message}`,'error')}};
$('#upload').onclick=async()=>{const file=$('#firmware').files[0];if(!file){setStatus('#otaStatus','Choose a .bin file first.','error');return}if(!state.base)state.base=base();setStatus('#otaStatus','Uploading… keep the sign powered on.');try{await api('/api/ota',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});setStatus('#otaStatus','Upload accepted. The sign is rebooting; check its LCD or /api/status.','ok')}catch(err){setStatus('#otaStatus',`OTA failed: ${err.message}`,'error')}};
